name: ui_components
description: UI components package for the Flutter UI Kit
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Internal dependencies
  ui_tokens:
    path: ../ui_tokens
    
  # Core dependencies
  flutter_svg: ^2.0.10+1
  animations: ^2.0.11
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
