name: example
description: Example app for UI Components
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Local dependencies
  ui_components:
    path: ..
  ui_tokens:
    path: ../../ui_tokens
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
